---

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: babel-eslint

settings:
  import/resolver:
    webpack:
      config: 'webpack.config.js'

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:react/recommended'
  - 'plugin:lodash-fp/recommended'

rules:
  no-console: 0
